#!/bin/sh

# Uptime-Kuma FreeBSD Service Script

# PROVIDE: uptimekuma
# REQUIRE: DAEMON NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name=uptimekuma
desc="Uptime-Kuma Website Monitoring"
rcvar=uptimekuma_enable

load_rc_config $name

: ${uptimekuma_enable:="NO"}
: ${uptimekuma_datadir:="/mnt/data"}
: ${uptimekuma_host:="0.0.0.0"}
: ${uptimekuma_port:="3001"}
: ${uptimekuma_chdir:="/usr/local/uptime-kuma"}
: ${uptimekuma_user:="uptimekuma"}
: ${uptimekuma_group:="uptimekuma"}

pidfile="/var/run/${name}/${name}.pid"
uptimekuma_env="PLAYWRIGHT_BROWSERS_PATH=/nonexistent"
node="/usr/local/bin/node"
command=/usr/sbin/daemon
command_args="-P ${pidfile} -H -o /var/log/${name}/${name}.log ${node} server/server.js --host=${uptimekuma_host} --port=${uptimekuma_port} --data-dir=${uptimekuma_datadir}"

start_precmd=uptimekuma_startprecmd

uptimekuma_startprecmd()
{
    if [ ! -d /var/run/${name} ]; then
        install -d -o ${uptimekuma_user} -g ${uptimekuma_group} /var/run/${name};
    else
        chown -R ${uptimekuma_user}:${uptimekuma_group} /var/run/${name};
    fi
    if [ ! -d /var/log/${name} ]; then
        install -d -o ${uptimekuma_user} -g ${uptimekuma_group} /var/log/${name};
    else
        chown -R ${uptimekuma_user}:${uptimekuma_group} /var/log/${name};
    fi
}

run_rc_command "$1"
