#!/bin/sh
#
# Uptime-Kuma FreeBSD Service Script
#
#

# PROVIDE: uptimekuma
# REQUIRE: DAEMON NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name=uptimekuma
desc="Uptime-Kuma Website Monitoring"
rcvar=uptimekuma_enable

load_rc_config $name

: ${uptimekuma_enable:="NO"}
: ${uptimekuma_datadir:="--data-dir=/mnt/data"}
: ${uptimekuma_host:="--host=0.0.0.0"}
: ${uptimekuma_chdir:="/usr/local/uptime-kuma"}
: ${uptimekuma_rundir:="/var/run/${name}"}
: ${uptimekuma_logdir:="/var/log/${name}"}
: ${uptimekuma_pidfile:="${uptimekuma_rundir}/${name}.pid"}
: ${uptimekuma_logfile:="${uptimekuma_logdir}/${name}.log"}

user=uptimekuma
group=uptimekuma
uptimekuma_env="PLAYWRIGHT_BROWSERS_PATH=/nonexistent"
node="/usr/local/bin/node"
command=/usr/sbin/daemon
command_args="-u ${user} -P ${meshcentral_pidfile} -H -o ${uptimekuma_logfile} ${node} server/server.js ${uptimekuma_host} ${uptimekuma_datadir}"

start_precmd=uptimekuma_startprecmd

uptimekuma_startprecmd()
{
    if [ ! -d ${uptimekuma_rundir} ]; then
        install -d -o ${user} -g ${group} ${uptimekuma_rundir};
    else
        chown -R ${user}:${group} ${uptimekuma_rundir};
    fi
    if [ ! -d ${uptimekuma_logdir} ]; then
        install -d -o ${user} -g ${group} ${uptimekuma_logdir};
    else
        chown -R ${user}:${group} ${uptimekuma_logdir};
    fi
}

run_rc_command "$1"
