#!/bin/sh

# MeshCentral FreeBSD Service Script

# PROVIDE: meshcentral
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name=meshcentral
desc="MeshCentral Computer Management"
rcvar=meshcentral_enable

load_rc_config $name

: ${meshcentral_enable:="NO"}
: ${meshcentral_args:=""}
: ${meshcentral_chdir:="/usr/local/meshcentral"}
: ${meshcentral_daemon_user:="meshcentral"}
: ${meshcentral_daemon_group:="meshcentral"}

pidfile="/var/run/${name}/${name}.pid"
node="/usr/local/bin/node"
command="/usr/sbin/daemon"
command_args="-u ${meshcentral_daemon_user} -P ${pidfile} -H -o /var/log/${name}/${name}.log ${node} node_modules/${name} ${meshcentral_args}"

start_precmd="meshcentral_startprecmd"

meshcentral_startprecmd()
{
    if [ ! -d /var/run/${name} ]; then
        install -d -o ${meshcentral_daemon_user} -g ${meshcentral_daemon_group} /var/run/${name};
    else
        chown -R ${meshcentral_daemon_user}:${meshcentral_daemon_group} /var/run/${name};
    fi
    if [ ! -d /var/log/${name} ]; then
        install -d -o ${meshcentral_daemon_user} -g ${meshcentral_daemon_group} /var/log/${name};
    else
        chown -R ${meshcentral_daemon_user}:${meshcentral_daemon_group} /var/log/${name};
    fi
}

run_rc_command "$1"
