#!/bin/sh
#
# PROVIDE: slskd
# REQUIRE: DAEMON NETWORKING
# KEYWORD: shutdown
#
# Optional settings:
# slskd_enable (YES/NO): Enable or disable the service.
# slskd_user (system user): User to run the service as.
# slskd_group (system group): Group to run the service as.
# slskd_appdir (path): Path to application data.
# slskd_config (path): Path to config file.

. /etc/rc.subr

name=slskd
rcvar=slskd_enable

load_rc_config $name

: ${slskd_enable:="NO"}
: ${slskd_appdir:="/usr/local/www/slskd"}
: ${slskd_config:="${slskd_appdir}/${name}.yml"}
: ${slskd_user:="soulseek"}
: ${slskd_group:="soulseek"}

slskd_chdir="/root"
pidfile="/var/run/${name}/${name}.pid"
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -H -o /var/log/${name}/${name}.log ${slskd_appdir}/${name} --app-dir=${slskd_appdir} --config=${slskd_config}"

start_precmd=${name}_startprecmd

${name}_startprecmd()
{
    mkdir -p /var/run/${name}
    mkdir -p /var/log/${name}
    chown -R ${slskd_user}:${slskd_group} /var/run/${name}
    chown -R ${slskd_user}:${slskd_group} /var/log/${name}
}

run_rc_command "$1"
