name: shellcheck

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    name: Run ShellCheck
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        env:
          # Excluding SC3037: In POSIX sh, echo flags are undefined. Ignoring
          #                   temporarily until we decide to keep it or use
          #                   printf instead
          SHELLCHECK_OPTS: -e SC3037
        with:
          severity: warning
          scandir: "."
